version: "3.2"

services:

  talaron:
    container_name: talaron-node
    image: node:17-alpine3.14
    volumes: 
     - ../talaron/:/app
    networks:
      - default_network
    ports:
      - 3500:3500
    command: node /app/server.js
    environment:
      - TALARON_PORT=3500
      - JWT_PRIVATE_KEY_PATH=/app/jwtRS256.key
      - JWT_PUBLIC_KEY_PATH=/app/jwtRS256.pem
      - REDIS_URL=redis://redis:6379
      - REDIS_PASS=ANf3Mgx6nseCbZpu

networks:
  default_network:
      driver: bridge